/trd/beam/particle e-
/trd/beam/momentum 1.0 GeV
/trd/radiator/enabled true
/trd/radiator/material G4_POLYETHYLENE
/trd/radiator/model gammaR
/trd/radiator/foilThickness 15 um
/trd/radiator/gapThickness 300 um
/trd/radiator/totalLength 31500 um
/trd/mode/trOnly true
/trd/scoring/exitFlux true
/trd/scoring/exitDistance 0 um
/trd/output/directory simulation2/root/gamma/gamma_1957
/run/initialize
/run/beamOn 10000
